### ISSUE TITLE
[Jsecond] Ошибка

### ISSUE THREAD

**Issue by pavel-b-novikov** [15202-sidorov/nsudotnet#5]
Возникнет, если я напишу так
```csharp
Js<int,object>.Function(x=>2)
```

Исправьте её

**Comment by 15202-sidorov** [comment]
```csharp
И так по индукции
public class JS<T1, T2> : JS<T1>
    {
        public static string Function(Expression<Func<T1, T2, object>> expression,
                                      string name="")
        {
            return Function(expression.Body,
                            expression.Parameters,
                            name);
        }
    }
```

**Comment by pavel-b-novikov** [comment]
Да вы, батенька, извращенец. Давайте нормальное решение соображайте.

**Comment by 15202-sidorov** [comment]
Вот тут не могу ничего сообразить. Я правильно понимаю, что задача в том, чтобы корректно преобразовать Expression<Func<T1,T2,object>> к Expression<Func<T1,object>>? И как тут Unary Expression использовать. Что-то недопонимаю... Можете еще подсказать?

**Comment by pavel-b-novikov** [comment]
Так, вы неправильно поняли задачу. 
Можно написать так
```csharp
Js<int,int>.Function(x=>-2)
```
И, кстати, я только что заметил что ваша программа этот случай обработает некорректно. И это надо починить

А можно написать вот так
```csharp
Js<int,object>.Function(x=>-2)
```
И вот на этом моменте обычно вываливается ошибка.

**Comment by 15202-sidorov** [comment]
Что-то странно. Смотрите, если проблема не с количеством принимаемых параметров, а с их типами, то в моей программе(по крайней мере у меня на компьютере)  выражение
```csharp 
JS<int,object>.Function(x=>-2);
```
обрабатывается вполне корректно в VisitConstant : function(x) { return -2; }
Однако да, проблема в унарными операциями была, и увидеть это можно было, например в этом случае
```csharp
JS<int,object>.Function(x=> -x);
//output : function(x) { return x; } 
```
Решил я ее создав еще один классец вида:
```csharp
 class JsUnaryExpression: JSExpression
    {
        public JsUnaryExpression(JSExpression right,
                                 string operation)
        {
            _right = right;
            _operation = operation;
        }

        public override string ToString()
        {
            return $"({_operation}{_right})";
        }

        private JSExpression _right;
        private string _operation;
}
```
И прописав в визиторе следующее
```csharp
protected override Expression VisitUnary(UnaryExpression node)
        {
            Visit(node.Operand);
            if ( node.NodeType == ExpressionType.Convert )
            {
                return node;
            }

            _expressionsStack.Push(new JsUnaryExpression(_expressionsStack.Pop(),
                                                         _operatorConvertionDictionary[node.NodeType]));
            return node;
        }
```
JS не типизирован, поэтому операции приведения типов можно опустить.
Вот, как то так.

**Comment by pavel-b-novikov** [comment]
Вы молодец. Приходите в четверг за четверкой.
